### ISSUE TITLE
Upgrading to version 2.40.2 breaks SCSS compilation

### ISSUE THREAD

**Issue by akieling** [patternfly/patternfly-next#2404]
Project [hawtio-core](https://github.com/hawtio/hawtio-core) currently depends on @patternfly/patternfly version 2.31.4 and builds fine.
When @patternfly/patternfly is upgraded to version 2.40.2, the Gulp task that compiles the SCSS fails.

Error message:

```
$ npx gulp sass
[hawtio-backend] Adding startup task
[hawtio-backend] Adding startup task
[hawtio-backend] Adding startup task
[09:17:48] Using gulpfile ~/dev/projects/hawtio/hawtio-core/gulpfile.js
[09:17:48] Starting 'clean'...
[09:17:48] Finished 'clean' after 3.16 ms
[09:17:48] Starting 'sass'...
[09:17:48] Finished 'sass' after 3.83 ms

events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: node_modules/@patternfly/patternfly/patternfly.scss
Error: File to import not found or unreadable: ./components/all.
        on line 5 of node_modules/@patternfly/patternfly/patternfly.scss
        from line 5 of src/patternfly.scss
>> @import "./components/all";

   ^

    at options.error (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/node-sass/lib/index.js:291:26)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:198:13)
    at onwriteError (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/readable-stream/lib/_stream_writable.js:439:12)
    at onwrite (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/readable-stream/lib/_stream_writable.js:460:11)
    at WritableState.onwrite (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/readable-stream/lib/_stream_transform.js:93:3)
    at errorM (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/gulp-sass/index.js:118:12)
    at Object.callback (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/gulp-sass/index.js:127:16)
    at options.error (/home/akieling/dev/projects/hawtio/hawtio-core/node_modules/node-sass/lib/index.js:294:32)
```

Project references:

- https://github.com/hawtio/hawtio-core/blob/127284eb8826dbf2eb929e9143c3c5d2a0681969/gulpfile.js#L61-L67
- https://github.com/hawtio/hawtio-core/blob/master/src/patternfly.scss

**Comment by redallen** [comment]
We just need to add `src('./src/patternfly/**/_all.scss').pipe(dest('./dist'));` to https://github.com/patternfly/patternfly-next/blob/master/gulpfile.js#L114 and verify it gets copied to the dist. We should also add some docs for how to compile our `patternfly.scss` yourself (and the experimental build toggling), and the shortcomings of our magical build-time comments for individual components.

From a project perspective, we want to put all the config for experimental components in a file other than that `components/_all.scss`, so that's why we aren't exporting it now. I'm happy to export it in the interim, but please be aware our build process might change in the future because of this and you'll end up with a broken build again.
